version: "3.8"
services:
  mysql:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    restart: always
  web:
    build: ./web
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    restart: on-failure

