name: docker-compose-build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and up
        run: |
          docker-compose up --build -d
          docker ps
          docker-compose exec web curl -v http://localhost:5000
        working-directory: ./

