name: docker-compose-build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubunutu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: compose-run
        shell: bash
        run: |
          docker-compose up -d
          curl http://localhost:5000/
