name: docker-compose-build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and up
        run: |
          docker-compose up --build -d
          curl http://localhost:5000/
        working-directory: ./

